- src/App.tsx
- src/pages/HistoryPembeli.tsx
- src/pages/Profile.tsx
slicing page history pembelian with responsive
> feat: slicing history pembelian

- src/App.tsx
- src/components/Navbar.tsx
- src/pages/HistoryPembeli.tsx
- src/pages/NotifikasiCoba.tsx
close #23 
slicing feedback with responsive
> Slicing feedback

- src/App.tsx
- src/main.tsx
- src/pages/Login.tsx
- src/utils/redux/reducer/reducer.ts
- src/utils/redux/store/store.ts
- src/utils/types/DataType.tsx
- src/utils/types/redux.ts
- vite.config.ts
1. integrasi login and save token in cookie
2. add loading
> Integrasi login

- src/pages/HistoryPembeli.tsx
- src/pages/Profile.tsx
1. restyle modal feedback reusable
2. integrasi add feddback
> feat: integrasi add feddback and restyle : change modal feedback to modal reusable

- src/components/ProdukCard.tsx
- src/pages/Detail.tsx
- src/pages/HistoryPembeli.tsx
- src/pages/Home.tsx
> feat: integrasi get product by id in home

- src/App.tsx
- src/pages/Login.tsx
- src/pages/Profile.tsx
- src/utils/redux/reducer/reducer.ts
1. integrasi change password and 
2. slicing modal change password
> feat: integrasi change password and slicing modal change password

- src/App.tsx
- src/components/Layout.tsx
- src/components/Navbar.tsx
- src/pages/Home.tsx
- src/pages/Login.tsx
- src/pages/Profile.tsx
1. conditional login and logout
2. fix remove cookie logout 
3. get name, email from cookie
> feat: add conditional login and logout. refactor : fix remove cookie logout and get name, email from cookie

- src/index.css
- src/pages/Login.tsx
responsive login
1. monitor
2. laptop
3. tablet
4. mobile
> style: responsive

- src/pages/Login.tsx
- src/pages/Profile.tsx
- src/pages/Register.tsx
1. responsive page register for PC, Laptop, Tablet, Mobile
2. conditional button disable page register
3. fix conditional disable button modal change password
> style: restyle responsive register. Feat : conditional button disable, Refactor : fix conditional disable button change password

- src/components/Navbar.tsx
- src/pages/Home.tsx
- src/pages/Profile.tsx
responsive page profile for PC, Laptop, Tablet, Mobile
> style: restyle responsive

- src/components/CustomButton.tsx
- src/components/CutomInput.tsx
- src/components/Modal.tsx
- src/pages/Profile.tsx
responsive modal change password
> style: responsive modal change password

- src/components/Navbar.tsx
- src/pages/Login.tsx
1. remove get cookie in login page
2. get data user in navbar with axios
> refactor: change get cookie in login and get data user with axios in navbar

- index.html
- src/components/Layout.tsx
- src/components/Navbar.tsx
- src/components/ProdukCard.tsx
- src/pages/Cart.tsx
- src/pages/Detail.tsx
- src/pages/Home.tsx
- src/pages/Profile.tsx
- src/pages/Toko.tsx
- tailwind.config.cjs
1. add darkMode 
2. add new Profile Foto
3. re-integrate Toko Penjual
> Feat : add darkmode ,  add new Profile Photo , Refactor : tokoPenjual

- package-lock.json
- package.json
- src/components/CustomButton.tsx
- src/components/FeedbackCard.tsx
- src/components/Layout.tsx
- src/components/Navbar.tsx
- src/pages/Detail.tsx
- src/pages/HistoryPembeli.tsx
- src/pages/Home.tsx
- src/pages/Login.tsx
- src/pages/NotifikasiCoba.tsx
- src/pages/Profile.tsx
- src/pages/Register.tsx
- src/utils/types/DataType.tsx
1. conditional profile
2. conditional navbar
3. restyle responsive history page
4. add load more with windows scrolling (bug)
> Responsive history

- src/pages/Detail.tsx
- src/pages/Payment.tsx
1. restyle discussion
2. conditional display discussion
> Styling and conditional display discussion

- src/components/CartCard.tsx
- src/pages/Cart.tsx
- src/pages/Payment.tsx
1. fix function in checkbox
2. function for delete from cart
3. styling darkmode and responsive
> refactor: fixed function in checkbox

- src/components/Navbar.tsx
- src/pages/Home.tsx
- src/pages/ListProduct.tsx
- src/pages/Payment.tsx
- src/pages/Profile.tsx
1. delete cart item after pay
2. alert in home if data user uncompleted
> Feat: Delete After Pay

- src/App.tsx
- src/components/ChatModal.tsx
- src/pages/Detail.tsx
- src/utils/types/DataType.tsx
> feat: integrasi chat

- src/components/ChatModal.tsx
> refactor: fix intergrasi chat

- package-lock.json
- package.json
- src/components/CardHistory.tsx
- src/pages/Detail.tsx
- src/pages/HistoryPembeli.tsx
- src/pages/HomeFilterPage.tsx
- src/pages/ListProduct.tsx
- src/utils/types/DataType.tsx
1. restyle with collapsable
2. add function add feedback
> Slice Add Feedback and responsive

- README.md
> docs: add readme.docs
